menu:
    - name: home
      path: /
      renderTemplates: index
    - name: hello
      path: hello.html
      renderTemplates: index

templatesCss:
    - name: index
      cssPath: src/css/index.css